%Make fixed point iterations generated by g(x).

%initital condition
x=1.3;
%number of iterations
N_it=10;

r=roots([1,4,0,-10]);
exact=r(3);

X=zeros(N_it,1);
X(1)=x;

Error=zeros(N_it,1);
Error(1)=abs(X(1)-exact);

%(function name)=@(x) (formula)
gg=@(x) sqrt(10./(4+x));

for k=1:N_it
    X(k+1)=gg(X(k));
    Error(k+1)=abs(X(k+1)-exact);
end